# I use global env to facilitate debug, since they exist as soon as you enter the shell
dist: xenial
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $HOME/.local/lib/R/]
env:
  global: 
    - input_git=https://github.com/hadley/r4ds.git
    - repo_git="-b hadley-r4ds https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"
    - rmd_dir=.
    - root_command=""   
    - user_command=""
    - install_pkg="remotes::update_packages('devtools'); remotes::install_github('hadley/r4ds')"
    - render_args=""
    - zhuoerdown=true # build other's bookdown, several links would be added to TOC
    - custom_yaml=$TRAVIS_BUILD_DIR/_output.yaml  
    - url=http://r4ds.had.co.nz/

script: wget https://raw.githubusercontent.com/dongzhuoer/zhuoerdown/master/inst/travis-script.sh && bash travis-script.sh

notifications:
  email: false
