dist: bionic
language: minimal
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files, $HOME/.local/lib/R/site-library]
script: bash -x build.sh
jobs:
  include:
    # if a book is not in GitHub, such as fool/weird in GitLab
    # then repo=dongzhuoer/gooddown rmd=gitlab/fool/weird niche=gitlab-fool/weird                
    - stage: build  
      name: place holder  
      script: skip  # without this toy job, comment first job would cuase error
    - name: rstudio/bookdown-demo
      env: repo=rstudio/bookdown-demo rmd=. niche=$repo apt="" url=https://bookdown.org/yihui/bookdown-demo
    - name: hadley/r4ds
      env: repo=hadley/r4ds rmd=. niche=$repo apt="" url=http://r4ds.had.co.nz
    - name: hadley/adv-r 
      env: repo=hadley/adv-r rmd=. niche=$repo apt="pandoc-citeproc" url=https://adv-r.hadley.nz
    - name: hadley/r-pkgs
      env: repo=hadley/r-pkgs rmd=. niche=$repo apt="" url=https://r-pkgs.org  
    - name: hadley/ggplot2-book
      env: repo=hadley/ggplot2-book rmd=. niche=$repo apt="libv8-dev libudunits2-dev libproj-dev libprotobuf-dev protobuf-compiler libgdal-dev libjq-dev" url=https://ggplot2-book.org  
    - name: rstudio/rmarkdown-book
      env: repo=rstudio/rmarkdown-book rmd=. niche=$repo apt="libmagick++-dev" url=https://bookdown.org/yihui/rmarkdown 
    - name: rstudio/bookdown
      env: repo=rstudio/bookdown rmd=inst/examples niche=$repo apt="libcairo2-dev texlive-latex-base" url=https://bookdown.org/yihui/bookdown 
    - name: rstudio/blogdown
      env: repo=rstudio/blogdown rmd=docs niche=$repo apt="libmagick++-dev" url=https://bookdown.org/yihui/blogdown 
    - name: tidyverse/design
      env: repo=tidyverse/design rmd=. niche=$repo apt="" url=http://design.tidyverse.org
    - name: tidyverse/style
      env: repo=tidyverse/style rmd=. niche=$repo apt="" url=http://style.tidyverse.org
    - name: tidyverse/tidyeval
      env: repo=tidyverse/tidyeval rmd=. niche=$repo apt="" url=https://tidyeval.tidyverse.org
    - name: yihui/r-ninja
      env: repo=yihui/r-ninja rmd=. niche=$repo apt="" url=https://bookdown.org/yihui/r-ninja 
    - stage: deploy
      name: trigger build-website to merge all books into one branch  
      script: wget https://github.com/dongzhuoer/build-website/raw/master/trigger.sh && bash -x trigger.sh bookdown

