dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$HOME/_bookdown_files/, $HOME/site-library]

jobs:
  include:
    - stage: build                
      name: yihui/bookdown-demo
      env: a=1            
      script: echo yihui bookdown-demo
    - name: yihui/r-ninja            
      script: echo yihui r-ninja
    - stage: deploy
      name: merge into gh-pages  
      script: 
        - echo deploy

notifications:
  email: false


# addons:
#   apt:
#     packages: pandoc
# env:
#   global: 
#     - repo_git="-b gh-pages https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"

# before_install: mkdir -p $HOME/.output/{hadley,yihui,zhuoer}
# install:
#   - git clone --depth 1 -b hadley-r4ds           https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/r4ds
#   - git clone --depth 1 -b hadley-adv-r          https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/adv-r
#   - git clone --depth 1 -b hadley-r-pkgs         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/r-pkgs
#   - git clone --depth 1 -b hadley-style          https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/style
#   - git clone --depth 1 -b hadley-tidyeval       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/tidyeval
#   - git clone --depth 1 -b yihui-bookdown-demo   https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/bookdown-demo     
#   - git clone --depth 1 -b yihui-bookdown        https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/bookdown     
#   - git clone --depth 1 -b yihui-blogdown        https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/blogdown     
#   - git clone --depth 1 -b yihui-rmarkdown       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/rmarkdown     
#   - git clone --depth 1 -b yihui-r-ninja         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/r-ninja     
#   - git clone --depth 1 -b zhuoer-nutshell       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/zhuoer/nutshell
#   - git clone --depth 1 -b zhuoer-thesis         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/zhuoer/thesis
#   - rm -rf $HOME/.output/*/*/{.git,*.md}
# before_script: mkdir $HOME/.repo
# script:
#   - pandoc index.md -s -o $HOME/.output/index.html
#   - echo "bookdown.dongzhuoer.com" > $HOME/.output/CNAME
#   - curl -o $HOME/.output/readme.md https://gist.githubusercontent.com/dongzhuoer/c19d456cf8c1bd977a2f7916f61beee8/raw/cc-license.md
#   - git clone --depth 1 $repo_git $HOME/.repo && mv $HOME/.repo/.git $HOME/.output
#   - cd $HOME/.output && git add --all && git commit -m "travis build at `date '+%Y-%m-%d %H:%M:%S'`" --allow-empty && git push -f

