dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $TRAVIS_BUILD_DIR/library]
env:
  - user=yihui repo=bookdown-demo
  - user=yihui repo=r-ninja
jobs:
  include:
    - stage: deploy
      script: echo deploy

script:
  - mkdir -p _bookdown_files/$user/$repo
  - mkdir -p library/$user/$repo

notifications:
  email: false
