dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$HOME/_bookdown_files/, $HOME/site-library]

jobs:
  include:
    - stage: build                
      name: yihui/bookdown-demo            
      script: echo yihui bookdown-demo
    - name: yihui/r-ninja            
      script: echo yihui r-ninja
    - stage: deploy
      script: 
        - echo deploy

notifications:
  email: false
