dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $TRAVIS_BUILD_DIR/library]
env:
  - user=yihui repo=bookdown-demo
  - user=yihui repo=r-ninja
jobs:
  include:
    - stage: deploy
      script: 
        - ls -Rhl _bookdown_files library

script:
  - mkdir -p _bookdown_files/$user/$repo
  - touch _bookdown_files/$user/$repo/haha
  - mkdir -p library/$user/$repo
  - touch library/$user/$repo/xixi

notifications:
  email: false
