dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $HOME/.local/lib/R/site-library]

jobs:
  include:
    # if a book is not in GitHub, such as fool/weird in GitLab
    # then repo=dongzhuoer/gooddown wd=gitlab/fool/weird niche=gitlab-fool/weird                
    - stage: build  
      name: rstudio/bookdown-demo
      env: repo=rstudio/bookdown-demo wd=. niche=$repo apt="" url=https://bookdown.org/yihui/bookdown-demo
    - name: hadley/r4ds
      env: repo=hadley/r4ds wd=. niche=$repo apt="" url=http://r4ds.had.co.nz
    - name: hadley/adv-r 
      env: repo=hadley/adv-r wd=. niche=$repo apt="pandoc-citeproc" url=https://adv-r.hadley.nz
    - name: hadley/r-pkgs
      env: repo=hadley/adv-r wd=. niche=$repo apt="" url=https://r-pkgs.org
    - name: tidyverse/style
      env: repo=tidyverse/style wd=. niche=$repo apt="" url=http://style.tidyverse.org
    - name: tidyverse/tidyeval
      env: repo=tidyverse/tidyeval wd=. niche=$repo apt="" url=https://tidyeval.tidyverse.org
    - name: yihui/r-ninja
      env: repo=yihui/r-ninja wd=. niche=$repo apt="" url=https://bookdown.org/yihui/r-ninja 
    - name: rstudio/rmarkdown-book
      env: repo=rstudio/rmarkdown-book wd=. niche=$repo apt="libmagick++-dev" url=https://bookdown.org/yihui/rmarkdown 
    - name: rstudio/bookdown
      env: repo=rstudio/bookdown wd=inst/examples niche=$repo apt="libcairo2-dev texlive-latex-base" url=https://bookdown.org/yihui/bookdown 
    - name: rstudio/blogdown
      env: repo=rstudio/blogdown wd=docs niche=$repo apt="libmagick++-dev" url=https://bookdown.org/yihui/blogdown 
    - stage: deploy
      name: merge into gh-pages  
      script: 
        - echo deploy

script: bash -x build.sh

notifications:
  email: false


# addons:
#   apt:
#     packages: pandoc
# env:
#   global: 
#     - repo_git="-b gh-pages https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"

# before_install: mkdir -p $HOME/.output/{hadley,yihui,zhuoer}
# install:
#   - git clone --depth 1 -b hadley-r4ds           https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/r4ds
#   - git clone --depth 1 -b hadley-adv-r          https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/adv-r
#   - git clone --depth 1 -b hadley-r-pkgs         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/r-pkgs
#   - git clone --depth 1 -b hadley-style          https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/style
#   - git clone --depth 1 -b hadley-tidyeval       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/hadley/tidyeval
#   - git clone --depth 1 -b yihui-bookdown-demo   https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/bookdown-demo     
#   - git clone --depth 1 -b yihui-bookdown        https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/bookdown     
#   - git clone --depth 1 -b yihui-blogdown        https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/blogdown     
#   - git clone --depth 1 -b yihui-rmarkdown       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/rmarkdown     
#   - git clone --depth 1 -b yihui-r-ninja         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/yihui/r-ninja     
#   - git clone --depth 1 -b zhuoer-nutshell       https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/zhuoer/nutshell
#   - git clone --depth 1 -b zhuoer-thesis         https://github.com/dongzhuoer/bookdown.dongzhuoer.com.git $HOME/.output/zhuoer/thesis
#   - rm -rf $HOME/.output/*/*/{.git,*.md}
# before_script: mkdir $HOME/.repo
# script:
#   - touch .nojekyll
#   - pandoc index.md -s -o $HOME/.output/index.html
#   - echo "bookdown.dongzhuoer.com" > $HOME/.output/CNAME
#   - curl -o $HOME/.output/readme.md https://gist.githubusercontent.com/dongzhuoer/c19d456cf8c1bd977a2f7916f61beee8/raw/cc-license.md
#   - git clone --depth 1 $repo_git $HOME/.repo && mv $HOME/.repo/.git $HOME/.output
#   - cd $HOME/.output && git add --all && git commit -m "travis build at `date '+%Y-%m-%d %H:%M:%S'`" --allow-empty && git push -f

