dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$HOME/_bookdown_files/, $HOME/site-library]
env:
  - user=yihui repo=bookdown-demo
  - user=yihui repo=r-ninja
jobs:
  include:
    - stage: deploy
      script: 
        - ls -hl $HOME/_bookdown_files $HOME/library

script:
  - echo hello

notifications:
  email: false
