dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$HOME/_bookdown_files/, $HOME/site-library]

jobs:
  include:
    - stage: build                
      name: yihui/bookdown-demo            
      script: mkdir -p output/yihui/bookdown-demo && echo yihui bookdown-demo
    - name: yihui/r-ninja            
      script: mkdir -p output/yihui/r-ninja && echo yihui r-ninja
    - stage: deploy
      name: merge into gh-pages  
      script: 
        - echo deploy
        - ls output/* -hl

notifications:
  email: false
