dist: bionic
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $TRAVIS_BUILD_DIR/library]
directory:
  - yihui/bookdown-demo
  - yihui/r-ninja
# env:
#   - user=yihui repo=bookdown-demo
#   - user=yihui repo=r-ninja
jobs:
  include:
    - stage: deploy
      script: 
        - ls -Rhl _bookdown_files library

script:
  - echo hello

notifications:
  email: false
