# I use global env to facilitate debug, since they exist as soon as you enter the shell
dist: xenial
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $HOME/.local/lib/R/]
env:
  global: 
    - input_git=https://github.com/rstudio/rmarkdown-book.git
    - repo_git="-b yihui-rmarkdown  https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"
    - rmd_dir=.
    - root_command="apt update && apt -y install libmagick++-dev"   
    - user_command=""
    - install_pkg="remotes::install_github('jjallaire/sigma'); remotes::update_packages(c('blogdown', 'htmlwidgets', 'webshot', 'xaringan', 'animation', 'pkgdown', 'tinytex', 'reticulate', 'JuliaCall', 'DT', 'leaflet', 'dygraphs', 'shiny', 'markdown',  'flexdashboard', 'tufte', 'revealjs', 'prettydoc', 'rticles', 'learnr', 'rmdformats'))"
    - render_args=""
    - zhuoerdown=true # build other's bookdown, several links would be added to TOC
    - custom_yaml=$TRAVIS_BUILD_DIR/_output.yaml  
    - url=https://bookdown.org/yihui/rmarkdown

script: wget https://raw.githubusercontent.com/dongzhuoer/zhuoerdown/master/inst/travis-script.sh && bash travis-script.sh

notifications:
  email: false
