# I use global env to facilitate debug, since they exist as soon as you enter the shell
dist: xenial
language: minimal
git:
  depth: false
  submodules: false
cache: 
  directories: [$TRAVIS_BUILD_DIR/_bookdown_files/, $HOME/.local/lib/R/]
env:
  global: 
    - input_git=https://github.com/tidyverse/tidyeval.git
    - repo_git="-b hadley-tidyeval  https://$GITHUB_PAT@github.com/dongzhuoer/bookdown.dongzhuoer.com.git"
    - rmd_dir=.
    - root_command=""   
    - user_command=""
    - install_pkg="remotes::update_packages(c('bookdown', 'dplyr', 'ggplot2', 'purrr', 'rlang'))"
    - render_args=""
    - zhuoerdown=true # build other's bookdown, several links would be added to TOC
    - custom_yaml=$TRAVIS_BUILD_DIR/_output.yaml  
    - url=https://tidyeval.tidyverse.org

script: wget https://raw.githubusercontent.com/dongzhuoer/zhuoerdown/master/inst/travis-script.sh && bash travis-script.sh

notifications:
  email: false

